version: "2.0"

services:
  web:
    image: nginx:alpine
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    command:
      - sh
      - -c
      - |
        cat > /usr/share/nginx/html/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>SentinelX - Secure Incident Reporting</title>
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            :root {
              --primary: #1a1a2e; --secondary: #16213e; --accent: #e94560;
              --text-primary: #ffffff; --text-secondary: #b8b8b8;
              --surface: #0f0f23; --surface-light: #252545; --border: #333366;
              --success: #00d4aa; --warning: #ffb800;
            }
            body {
              font-family: 'Poppins', sans-serif;
              background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 50%, var(--surface) 100%);
              min-height: 100vh; color: var(--text-primary); line-height: 1.6;
            }
            .navbar {
              background: rgba(15, 15, 35, 0.95); backdrop-filter: blur(20px);
              border-bottom: 1px solid var(--border); padding: 1rem 0;
              position: sticky; top: 0; z-index: 1000;
            }
            .nav-container {
              max-width: 1200px; margin: 0 auto; display: flex;
              justify-content: space-between; align-items: center; padding: 0 2rem;
            }
            .logo { display: flex; align-items: center; gap: 0.75rem; font-size: 1.5rem; font-weight: 700; }
            .logo i { color: var(--accent); font-size: 1.75rem; }
            .nav-links { display: flex; gap: 2rem; }
            .nav-link {
              color: var(--text-secondary); text-decoration: none; font-weight: 500;
              padding: 0.5rem 1rem; border-radius: 8px; transition: all 0.3s ease; cursor: pointer;
            }
            .nav-link:hover, .nav-link.active { color: var(--text-primary); background: var(--surface-light); }
            .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
            .section { display: none; animation: fadeIn 0.5s ease; }
            .section.active { display: block; }
            .hero { text-align: center; margin-bottom: 3rem; padding: 3rem 0; }
            .hero h1 {
              font-size: 3.5rem; font-weight: 700; margin-bottom: 1rem;
              background: linear-gradient(135deg, var(--text-primary) 0%, var(--accent) 100%);
              -webkit-background-clip: text; -webkit-text-fill-color: transparent;
            }
            .hero p { font-size: 1.25rem; color: var(--text-secondary); max-width: 600px; margin: 0 auto 2rem; }
            .btn {
              background: linear-gradient(135deg, var(--accent) 0%, #ff6b7a 100%);
              color: var(--text-primary); padding: 1rem 2rem; border: none; border-radius: 12px;
              font-size: 1rem; font-weight: 600; cursor: pointer; transition: all 0.3s ease;
              display: inline-flex; align-items: center; gap: 0.5rem; margin: 0.5rem;
            }
            .btn:hover { transform: translateY(-2px); box-shadow: 0 8px 24px rgba(233, 69, 96, 0.4); }
            .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 2rem; margin: 3rem 0; }
            .stat-card { background: var(--surface-light); padding: 2rem; border-radius: 16px; text-align: center; border: 1px solid var(--border); }
            .stat-number { font-size: 2.5rem; font-weight: 700; color: var(--accent); margin-bottom: 0.5rem; }
            .form-container { background: var(--surface-light); padding: 2rem; border-radius: 16px; border: 1px solid var(--border); max-width: 800px; margin: 0 auto; }
            .form-group { margin-bottom: 1rem; }
            label { display: block; margin-bottom: 0.5rem; font-weight: 500; }
            input, textarea, select {
              width: 100%; padding: 1rem; border: 2px solid var(--border); border-radius: 8px;
              background: var(--surface); color: var(--text-primary); font-family: inherit;
            }
            input:focus, textarea:focus, select:focus { outline: none; border-color: var(--accent); }
            .status { padding: 1rem; border-radius: 8px; margin: 1rem 0; border-left: 4px solid; }
            .status.success { background: rgba(0, 212, 170, 0.1); border-color: var(--success); color: var(--success); }
            .status.processing { background: rgba(255, 184, 0, 0.1); border-color: var(--warning); color: var(--warning); }
            @keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
            @media (max-width: 768px) { .hero h1 { font-size: 2.5rem; } .nav-links { display: none; } }
          </style>
        </head>
        <body>
          <nav class="navbar">
            <div class="nav-container">
              <div class="logo"><i class="fas fa-shield-alt"></i>SentinelX</div>
              <div class="nav-links">
                <a class="nav-link active" onclick="showSection('home')">Home</a>
                <a class="nav-link" onclick="showSection('report')">Report</a>
                <a class="nav-link" onclick="showSection('dashboard')">Dashboard</a>
              </div>
            </div>
          </nav>

          <div class="container">
            <div id="home" class="section active">
              <div class="hero">
                <h1>SentinelX Platform</h1>
                <p>Advanced AI-powered incident reporting with blockchain verification and enterprise-grade security</p>
                <button class="btn" onclick="showSection('report')"><i class="fas fa-plus"></i>Submit Report</button>
                <button class="btn" onclick="showSection('dashboard')"><i class="fas fa-chart-line"></i>Dashboard</button>
              </div>
              <div class="stats-grid">
                <div class="stat-card"><div class="stat-number">1,247</div><div>Reports Processed</div></div>
                <div class="stat-card"><div class="stat-number">8,934</div><div>Faces Protected</div></div>
                <div class="stat-card"><div class="stat-number">15,672</div><div>PII Entities Secured</div></div>
                <div class="stat-card"><div class="stat-number">99.7%</div><div>System Uptime</div></div>
              </div>
            </div>

            <div id="report" class="section">
              <div class="form-container">
                <h2 style="text-align: center; margin-bottom: 2rem;">Submit Secure Incident Report</h2>
                <form id="reportForm">
                  <div class="form-group">
                    <label><i class="fas fa-file-alt"></i> Incident Title</label>
                    <input type="text" id="title" placeholder="Brief description" required>
                  </div>
                  <div class="form-group">
                    <label><i class="fas fa-tags"></i> Category</label>
                    <select id="category" required>
                      <option value="">Select category...</option>
                      <option value="workplace">Workplace Harassment</option>
                      <option value="security">Security Breach</option>
                      <option value="fraud">Financial Fraud</option>
                      <option value="safety">Safety Violation</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label><i class="fas fa-exclamation-triangle"></i> Severity</label>
                    <select id="severity" required>
                      <option value="">Select severity...</option>
                      <option value="low">Low Impact</option>
                      <option value="medium">Medium Impact</option>
                      <option value="high">High Impact</option>
                      <option value="critical">Critical</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label><i class="fas fa-align-left"></i> Description</label>
                    <textarea id="description" rows="5" placeholder="Provide details..." required></textarea>
                  </div>
                  <button type="submit" class="btn" style="width: 100%;"><i class="fas fa-shield-alt"></i>Submit Secure Report</button>
                </form>
                <div id="report-status" style="display:none;"></div>
              </div>
            </div>

            <div id="dashboard" class="section">
              <h2 style="margin-bottom: 2rem;">Real-Time Analytics Dashboard</h2>
              <div class="stats-grid">
                <div class="stat-card"><h3>System Status</h3><p>GPU Utilization: 78%<br>Processing Queue: 12<br>Active Workers: 5</p></div>
                <div class="stat-card"><h3>Today's Metrics</h3><div class="stat-number">47</div><div>Reports Processed</div></div>
                <div class="stat-card"><h3>AI Insights</h3><p>Pattern Detected: 23% increase in security incidents<br>Recommendation: Deploy additional training</p></div>
              </div>
            </div>
          </div>

          <script>
            function showSection(sectionName) {
              document.querySelectorAll('.section').forEach(s => s.classList.remove('active'));
              document.querySelectorAll('.nav-link').forEach(l => l.classList.remove('active'));
              document.getElementById(sectionName).classList.add('active');
              event.target.classList.add('active');
            }

            document.getElementById('reportForm').addEventListener('submit', async (e) => {
              e.preventDefault();
              const statusDiv = document.getElementById('report-status');
              statusDiv.style.display = 'block';
              statusDiv.className = 'status processing';
              statusDiv.innerHTML = '<i class="fas fa-cog fa-spin"></i> Processing secure report...';
              
              setTimeout(() => {
                const reportId = 'report-' + Date.now();
                statusDiv.className = 'status success';
                statusDiv.innerHTML = `
                  <i class="fas fa-check-circle"></i> Report Successfully Processed<br>
                  Report ID: ${reportId}<br>
                  Blockchain Hash: 0x${Math.random().toString(16).substr(2, 16)}...
                `;
              }, 2000);
            });
          </script>
        </body>
        </html>
        EOF
        
        nginx -g 'daemon off;'

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 2Gi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    akash:
      profile: web
      count: 1