version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    
  api:
    build: ./gateway-api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    
  demo:
    build: ./local-test
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production