version: "2.0"

services:
  sentinelx:
    image: nginx:alpine
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    command:
      - sh
      - -c
      - |
        # Simple single container deployment
        cat > /usr/share/nginx/html/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>SentinelX - Live Demo</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
            .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; }
            .header { text-align: center; margin-bottom: 30px; }
            .btn { background: #007bff; color: white; padding: 12px 24px; border: none; border-radius: 4px; cursor: pointer; text-decoration: none; display: inline-block; }
            .feature { margin: 20px 0; padding: 20px; background: #f8f9fa; border-radius: 8px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>SentinelX - Secure Incident Reporting</h1>
              <p>Live on Akash Network - Hackathon Demo</p>
            </div>
            
            <div class="feature">
              <h3>🔐 End-to-End Encryption</h3>
              <p>Military-grade AES-256-GCM encryption protects all incident reports</p>
            </div>
            
            <div class="feature">
              <h3>🤖 AI-Powered Redaction</h3>
              <p>GPU-accelerated face detection and PII removal on Akash Network</p>
            </div>
            
            <div class="feature">
              <h3>⛓️ Blockchain Proof</h3>
              <p>Immutable audit trail on Ethereum for legal admissibility</p>
            </div>
            
            <div class="feature">
              <h3>🏢 Enterprise Ready</h3>
              <p>Multi-tenant architecture for Fortune 500 companies</p>
            </div>
            
            <div style="text-align: center; margin-top: 40px;">
              <a href="https://github.com/Rahul-Raval-2912/SentinelX" class="btn">View Source Code</a>
              <a href="#" class="btn" onclick="alert('Demo: Report submitted successfully! Processing with AI on Akash Network...')">Try Demo</a>
            </div>
            
            <div style="text-align: center; margin-top: 20px; color: #666;">
              <p>Deployed on Akash Network | 70% cheaper than traditional cloud</p>
              <p>Hackathon Submission - SentinelX Platform</p>
            </div>
          </div>
        </body>
        </html>
        EOF
        
        nginx -g 'daemon off;'

profiles:
  compute:
    sentinelx:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        sentinelx:
          denom: uakt
          amount: 50

deployment:
  sentinelx:
    akash:
      profile: sentinelx
      count: 1